CREATE
    EXTENSION postgis;
CREATE
    EXTENSION postgis_topology;
CREATE
    EXTENSION fuzzystrmatch;
CREATE
    EXTENSION postgis_tiger_geocoder;

create table user_services
(
    id            bigint generated by default as identity
        constraint user_services_pk
            primary key,
    created_at    timestamp(6) default now() not null,
    updated_at    timestamp(6),
    title         varchar,
    price         numeric      default 0,
    user_id       bigint                     not null,
    store_id      bigint                     not null,
    duration_time varchar,
    description   varchar,
    deleted_at    timestamp(6)
);

create table user_services_map
(
    id                 bigint generated by default as identity
        constraint user_services_map_pk
            primary key,
    created_at         timestamp(6) default now() not null,
    updated_at         timestamp(6),
    object_id          bigint                     not null,
    object_type        varchar                    not null,
    user_services_type varchar                    not null,
    user_services_id   bigint                     not null,
    constraint user_services_map_user_services_pk
        foreign key (user_services_id) references user_services (id)
);


