spring:
  application:
    name: authentication-service
  profiles:
    active: local

app:
  admin:
    account:
      username: ${AUTHENTICATION_ADMIN_USERNAME:admin}
      password: ${AUTHENTICATION_ADMIN_PASSWORD:Admin@12345}

server:
  port: 8080
  servlet:
    context-path: /authentication

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSZ}","level":"%p","service":"${spring.application.name:-unknown}","env":"${spring.profiles.active:-local}","thread":"%t","class":"%C{1}.%M:%L","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","requestId":"%X{requestId:-}","message":"%replace(%msg){"\n"," "}"}'
  file:
    name: logs/authentication_service.log
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


