spring:
  application:
    name: post-service
  profiles:
    active: local

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} | %-5level | %X{traceId:-N/A} | %thread | %C{1}.%M:%L | %msg%n"
  file:
    name: logs/post_service.log
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG

server:
  port: 8081
  servlet:
    context-path: /post

app:
  services:
    authentication:
      url: http://localhost:8080/authentication
    customer:
      url: http://localhost:8082/customer
