spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POST_DB_HOST:192.168.3.41}:${POST_DB_PORT:5432}/${POST_DB_NAME:customer}
    username: ${POST_DB_USER:root}
    password: ${POST_DB_PASSWORD:root}
    hikari:
      pool-name: "Customer_Service_Hikari_Pool"
      validation-timeout: 5000
      connection-test-query: "SELECT 1"
      keepalive-time: 300000
      auto-commit: false

      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
        query:
          in_clause_parameter_padding: true
          plan_cache_max_size: 2048
        default_schema: ${POST_DB_NAME:customer}
        open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
  data:
    redis:
      host: ${REDIS_HOST:192.168.3.41}
      port: ${REDIS_PORT:6379}
      connect-timeout: 10000
      timeout: 3000
      database: 0
      password:
      sentinel:
        master: ''
        nodes: ''
      jedis:
        pool:
          max-idle: 3
          min-idle: 2
          max-total: 300
          min-evictable-idle-time: 60000
          time-between-eviction-runs: 30000
          num-tests-per-eviction-run: 10
          max-wait: 1000
jwt:
  auth:
    converter:
      resource-id: ${keycloak.clientId}
      principal-attribute: preferred_username

keycloak:
  realm: ${KEYCLOAK_REALM:bka}
  domain: ${KEYCLOAK_HOST:192.168.3.41}:${KEYCLOAK_PORT:8090}
  clientId: ${KEYCLOAK_CLIENT_ID:bka_app}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET:JBIlGc9mx1WeLTGqgbhDTYUfftJBkrlK}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin123}
    realm: master
    clientId: admin-cli
  urls: http://${keycloak.domain}

minio:
  url: http://${MINIO_ENDPOINT:192.168.3.41:9000}
  username: ${MINIO_USERNAME:bkaadmin}
  password: ${MINIO_PASSWORD:bkaadmin}
  attachments-bucket: ${MINIO_ATTACHMENTS_BUCKET:attachment}